# Configuracoes da JVM do Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Habilita o cache de configuracao e o build paralelo
org.gradle.caching=true
org.gradle.parallel=true

# AndroidX obrigatorio no toolchain moderno
android.useAndroidX=true

# Kotlin: estilo oficial de code style
kotlin.code.style=official

# Gera apenas os recursos R por modulo (build mais rapido)
android.nonTransitiveRClass=true
